---
abstract: 'Install tests for L<POE::Loop>s'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Install-POE-Test-Loops
no_index:
  directory:
    - inc
    - t
provides:
  Module::Install::POE::Test::Loops:
    file: lib/Module/Install/POE/Test/Loops.pm
    version: 0.02
requires:
  POE::Test::Loops: 1.001
  perl: 5.005
version: 0.02
